AWSTemplateFormatVersion: 2010-09-09
Description: >-
  (SO0006-WebACL) - AWS WAF Security Automations v3.2.1: This AWS CloudFormation template helps
  you provision the AWS WAF Security Automations stack without worrying about creating and
  configuring the underlying AWS infrastructure.

Parameters:
  ActivateAWSManagedRulesParam:
    Type: String
    Default: Enabled
  ActivateSqlInjectionProtectionParam:
    Type: String
    Default: Disabled
  ActivateCrossSiteScriptingProtectionParam:
    Type: String
    Default: Disabled
  ActivateHttpFloodProtectionParam:
    Type: String
    Default: Disabled
  ActivateScannersProbesProtectionParam:
    Type: String
    Default: Disabled
  ActivateReputationListsProtectionParam:
    Type: String
    Default: Disabled
  ActivateBadBotProtectionParam:
    Type: String
    Default: Disabled
  ParentStackName:
    Type: String
    Default: MyWebACLStack

Resources:
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Ref 'ParentStackName'
      Description: 'Custom WAFWebACL'
      Scope: REGIONAL
      VisibilityConfig: 
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: WAFWebACLMetrics
      DefaultAction:
        Allow: {}
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRCRS
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet

    