AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This AWS CloudFormation template helps you provision the AWS WAF Bundle.

Parameters:
  AWSDistributorName:
    Type: String
    Default: AcmeCorp
    Description: Partner Name

  BundleName:
    Type: String
    Default: AWS_WAF_Bundle_lite
    Description: Name of the AWS bundle being deployed.

  WebACLName:
    Type: String
    Default: WebACL-WebApp1
    Description: Identify this Web ACL with a name (eg. webACL-customerName-webapp1)

  EndpointType:
    Type: String
    Default: REGIONAL
    AllowedValues:
      - 'CLOUDFRONT'
      - 'REGIONAL'
    Description: Select 'REGIONAL' for ALB/ELB/API Gateway endpoints and 'CLOUDFRONT' if Cloudfront is the endpoint.

  ActivateAWSManagedRulesParam:
    Type: String
    Default: yes
    AllowedValues:
      - yes
      - no
    Description: Choose yes to enable AWS Managed Rules

  ActivateReputationListsProtectionParam:
    Type: String
    Default: yes
    AllowedValues:
      - yes
      - no
    Description: >-
      Choose yes to block requests from IP addresses on third-party reputation lists (supported
      lists: spamhaus, torproject, and emerging threats).

  ReportingEnabled:
    Type: String
    Default: yes
    AllowedValues:
     - yes
     - no
    Description: Allow AWS to collect basic usage metrics about this deployment.

Conditions:
  AWSManagedCommonRulesActivated: !Equals [!Ref ActivateAWSManagedRulesParam, yes]
  ReputationListsProtectionActivated: !Equals [!Ref ActivateReputationListsProtectionParam, yes]
  isReportingEnabled: !Equals [!Ref ReportingEnabled, yes]

Metadata:
  AWS:CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Launch Configuration"
        Parameters:
          - WebACLName
          - EndpointType
          - ActivateAWSManagedRulesParam
          - ActivateReputationListsProtectionParam
      -
        Label:
          default: "Statistics Reporting"
        Parameters:
          - AWSDistributorName
          - BundleName
          - ReportingEnabled

    ParameterLabels:
      ActivateAWSManagedRulesParam:
        default: "Activate AWS Managed Rules?"
      ActivateReputationListsProtectionParam:
        default: "Activate Reputation Lists Protection?"

Resources:
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Ref WebACLName
      Description: 'Custom WAFWebACL'
      Scope: !Ref EndpointType
      VisibilityConfig: 
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: WAFWebACLMetrics
      DefaultAction:
        Allow: {}
      Rules:
        - Fn::If:
          - AWSManagedCommonRulesActivated
          - Name: AWS-AWSManagedRulesCommonRuleSet
            Priority: 0
            OverrideAction:
              None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: RuleWithAWSManagedRulesMetric
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesCommonRuleSet
          - Ref: AWS::NoValue

        - Fn::If:
          - ReputationListsProtectionActivated
          - Name: AWS-AWSManagedRulesAmazonIpReputationList
            Priority: 1
            OverrideAction:
              None: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: RuleWithAWSManagedRulesMetric
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesAmazonIpReputationList
          - Ref: AWS::NoValue

  sendStatistics:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub "https://s3.ap-south-1.amazonaws.com/aws-distribution-bundle-templates/cft_statsProcessor.yaml"
      Parameters:
        AWSDistributorName: !Ref AWSDistributorName
        BundleName: !Ref BundleName
      TimeoutInMinutes: 5
